import React from 'react';
export const metadata = {
     title: ' Payment | Asian IT ',
     description: 'Generated by create next app',
   };
const layout = ({children}) => {
     return (
          <div>
                {children}
          </div>
     );
};

export default layout;